# Generated by Django 5.1.6 on 2025-03-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('album', models.TextField(null=True)),
                ('artist', models.TextField()),
                ('duration_ms', models.TextField()),
                ('url', models.URLField(null=True)),
                ('added_at', models.DateField(null=True)),
            ],
        ),
    ]
