# Generated by Django 5.1.6 on 2025-03-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_spotifytoken_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
